// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MihomoEngine_Start_FullMethodName          = "/meowhomo.engine.MihomoEngine/Start"
	MihomoEngine_Stop_FullMethodName           = "/meowhomo.engine.MihomoEngine/Stop"
	MihomoEngine_Reload_FullMethodName         = "/meowhomo.engine.MihomoEngine/Reload"
	MihomoEngine_GetStatus_FullMethodName      = "/meowhomo.engine.MihomoEngine/GetStatus"
	MihomoEngine_GetConnections_FullMethodName = "/meowhomo.engine.MihomoEngine/GetConnections"
	MihomoEngine_GetTraffic_FullMethodName     = "/meowhomo.engine.MihomoEngine/GetTraffic"
	MihomoEngine_StreamLogs_FullMethodName     = "/meowhomo.engine.MihomoEngine/StreamLogs"
)

// MihomoEngineClient is the client API for MihomoEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeowHomo 内核管理 gRPC 接口
type MihomoEngineClient interface {
	// 启动引擎
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 停止引擎
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	// 重载配置
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// 获取引擎状态
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	// 获取活跃连接
	GetConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectionsResponse, error)
	// 获取流量统计
	GetTraffic(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrafficResponse, error)
	// 日志流（服务端推送）
	StreamLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
}

type mihomoEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMihomoEngineClient(cc grpc.ClientConnInterface) MihomoEngineClient {
	return &mihomoEngineClient{cc}
}

func (c *mihomoEngineClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) GetConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionsResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_GetConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) GetTraffic(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, MihomoEngine_GetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mihomoEngineClient) StreamLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MihomoEngine_ServiceDesc.Streams[0], MihomoEngine_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MihomoEngine_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

// MihomoEngineServer is the server API for MihomoEngine service.
// All implementations must embed UnimplementedMihomoEngineServer
// for forward compatibility.
//
// MeowHomo 内核管理 gRPC 接口
type MihomoEngineServer interface {
	// 启动引擎
	Start(context.Context, *StartRequest) (*StatusResponse, error)
	// 停止引擎
	Stop(context.Context, *Empty) (*StatusResponse, error)
	// 重载配置
	Reload(context.Context, *ReloadRequest) (*StatusResponse, error)
	// 获取引擎状态
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	// 获取活跃连接
	GetConnections(context.Context, *Empty) (*ConnectionsResponse, error)
	// 获取流量统计
	GetTraffic(context.Context, *Empty) (*TrafficResponse, error)
	// 日志流（服务端推送）
	StreamLogs(*Empty, grpc.ServerStreamingServer[LogEntry]) error
	mustEmbedUnimplementedMihomoEngineServer()
}

// UnimplementedMihomoEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMihomoEngineServer struct{}

func (UnimplementedMihomoEngineServer) Start(context.Context, *StartRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedMihomoEngineServer) Stop(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedMihomoEngineServer) Reload(context.Context, *ReloadRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedMihomoEngineServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMihomoEngineServer) GetConnections(context.Context, *Empty) (*ConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnections not implemented")
}
func (UnimplementedMihomoEngineServer) GetTraffic(context.Context, *Empty) (*TrafficResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTraffic not implemented")
}
func (UnimplementedMihomoEngineServer) StreamLogs(*Empty, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedMihomoEngineServer) mustEmbedUnimplementedMihomoEngineServer() {}
func (UnimplementedMihomoEngineServer) testEmbeddedByValue()                      {}

// UnsafeMihomoEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MihomoEngineServer will
// result in compilation errors.
type UnsafeMihomoEngineServer interface {
	mustEmbedUnimplementedMihomoEngineServer()
}

func RegisterMihomoEngineServer(s grpc.ServiceRegistrar, srv MihomoEngineServer) {
	// If the following call pancis, it indicates UnimplementedMihomoEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MihomoEngine_ServiceDesc, srv)
}

func _MihomoEngine_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_GetConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).GetConnections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_GetTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MihomoEngineServer).GetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MihomoEngine_GetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MihomoEngineServer).GetTraffic(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MihomoEngine_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MihomoEngineServer).StreamLogs(m, &grpc.GenericServerStream[Empty, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MihomoEngine_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

// MihomoEngine_ServiceDesc is the grpc.ServiceDesc for MihomoEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MihomoEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meowhomo.engine.MihomoEngine",
	HandlerType: (*MihomoEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _MihomoEngine_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _MihomoEngine_Stop_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _MihomoEngine_Reload_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MihomoEngine_GetStatus_Handler,
		},
		{
			MethodName: "GetConnections",
			Handler:    _MihomoEngine_GetConnections_Handler,
		},
		{
			MethodName: "GetTraffic",
			Handler:    _MihomoEngine_GetTraffic_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _MihomoEngine_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}
