// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mihomo 配置 YAML 内容
	ConfigYaml    string `protobuf:"bytes,1,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigYaml    string                 `protobuf:"bytes,1,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadRequest) GetConfigYaml() string {
	if x != nil {
		return x.ConfigYaml
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Connections   int32                  `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *StatusResponse) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*Connection          `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionsResponse) Reset() {
	*x = ConnectionsResponse{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionsResponse) ProtoMessage() {}

func (x *ConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionsResponse) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Proxy         string                 `protobuf:"bytes,4,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Rule          string                 `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"`
	UploadBytes   int64                  `protobuf:"varint,6,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes int64                  `protobuf:"varint,7,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	StartTime     int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Connection) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Connection) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *Connection) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Connection) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *Connection) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *Connection) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type TrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadTotal   int64                  `protobuf:"varint,1,opt,name=upload_total,json=uploadTotal,proto3" json:"upload_total,omitempty"`
	DownloadTotal int64                  `protobuf:"varint,2,opt,name=download_total,json=downloadTotal,proto3" json:"download_total,omitempty"`
	UploadSpeed   int64                  `protobuf:"varint,3,opt,name=upload_speed,json=uploadSpeed,proto3" json:"upload_speed,omitempty"`
	DownloadSpeed int64                  `protobuf:"varint,4,opt,name=download_speed,json=downloadSpeed,proto3" json:"download_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficResponse) Reset() {
	*x = TrafficResponse{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficResponse) ProtoMessage() {}

func (x *TrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficResponse.ProtoReflect.Descriptor instead.
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *TrafficResponse) GetUploadTotal() int64 {
	if x != nil {
		return x.UploadTotal
	}
	return 0
}

func (x *TrafficResponse) GetDownloadTotal() int64 {
	if x != nil {
		return x.DownloadTotal
	}
	return 0
}

func (x *TrafficResponse) GetUploadSpeed() int64 {
	if x != nil {
		return x.UploadSpeed
	}
	return 0
}

func (x *TrafficResponse) GetDownloadSpeed() int64 {
	if x != nil {
		return x.DownloadSpeed
	}
	return 0
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 日志来源角色
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// 日志级别: info, warn, error
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// 日志内容
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// 时间戳
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x0fmeowhomo.engine\"\a\n" +
	"\x05Empty\"/\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vconfig_yaml\x18\x01 \x01(\tR\n" +
	"configYaml\"0\n" +
	"\rReloadRequest\x12\x1f\n" +
	"\vconfig_yaml\x18\x01 \x01(\tR\n" +
	"configYaml\"\xc6\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12 \n" +
	"\vconnections\x18\x05 \x01(\x05R\vconnections\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"T\n" +
	"\x13ConnectionsResponse\x12=\n" +
	"\vconnections\x18\x01 \x03(\v2\x1b.meowhomo.engine.ConnectionR\vconnections\"\xe9\x01\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x14\n" +
	"\x05proxy\x18\x04 \x01(\tR\x05proxy\x12\x12\n" +
	"\x04rule\x18\x05 \x01(\tR\x04rule\x12!\n" +
	"\fupload_bytes\x18\x06 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\a \x01(\x03R\rdownloadBytes\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\"\xa5\x01\n" +
	"\x0fTrafficResponse\x12!\n" +
	"\fupload_total\x18\x01 \x01(\x03R\vuploadTotal\x12%\n" +
	"\x0edownload_total\x18\x02 \x01(\x03R\rdownloadTotal\x12!\n" +
	"\fupload_speed\x18\x03 \x01(\x03R\vuploadSpeed\x12%\n" +
	"\x0edownload_speed\x18\x04 \x01(\x03R\rdownloadSpeed\"p\n" +
	"\bLogEntry\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x84\x04\n" +
	"\fMihomoEngine\x12G\n" +
	"\x05Start\x12\x1d.meowhomo.engine.StartRequest\x1a\x1f.meowhomo.engine.StatusResponse\x12?\n" +
	"\x04Stop\x12\x16.meowhomo.engine.Empty\x1a\x1f.meowhomo.engine.StatusResponse\x12I\n" +
	"\x06Reload\x12\x1e.meowhomo.engine.ReloadRequest\x1a\x1f.meowhomo.engine.StatusResponse\x12D\n" +
	"\tGetStatus\x12\x16.meowhomo.engine.Empty\x1a\x1f.meowhomo.engine.StatusResponse\x12N\n" +
	"\x0eGetConnections\x12\x16.meowhomo.engine.Empty\x1a$.meowhomo.engine.ConnectionsResponse\x12F\n" +
	"\n" +
	"GetTraffic\x12\x16.meowhomo.engine.Empty\x1a .meowhomo.engine.TrafficResponse\x12A\n" +
	"\n" +
	"StreamLogs\x12\x16.meowhomo.engine.Empty\x1a\x19.meowhomo.engine.LogEntry0\x01B,Z*github.com/Waasaabii/meowhomo/engine/protob\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_engine_proto_goTypes = []any{
	(*Empty)(nil),               // 0: meowhomo.engine.Empty
	(*StartRequest)(nil),        // 1: meowhomo.engine.StartRequest
	(*ReloadRequest)(nil),       // 2: meowhomo.engine.ReloadRequest
	(*StatusResponse)(nil),      // 3: meowhomo.engine.StatusResponse
	(*ConnectionsResponse)(nil), // 4: meowhomo.engine.ConnectionsResponse
	(*Connection)(nil),          // 5: meowhomo.engine.Connection
	(*TrafficResponse)(nil),     // 6: meowhomo.engine.TrafficResponse
	(*LogEntry)(nil),            // 7: meowhomo.engine.LogEntry
}
var file_engine_proto_depIdxs = []int32{
	5, // 0: meowhomo.engine.ConnectionsResponse.connections:type_name -> meowhomo.engine.Connection
	1, // 1: meowhomo.engine.MihomoEngine.Start:input_type -> meowhomo.engine.StartRequest
	0, // 2: meowhomo.engine.MihomoEngine.Stop:input_type -> meowhomo.engine.Empty
	2, // 3: meowhomo.engine.MihomoEngine.Reload:input_type -> meowhomo.engine.ReloadRequest
	0, // 4: meowhomo.engine.MihomoEngine.GetStatus:input_type -> meowhomo.engine.Empty
	0, // 5: meowhomo.engine.MihomoEngine.GetConnections:input_type -> meowhomo.engine.Empty
	0, // 6: meowhomo.engine.MihomoEngine.GetTraffic:input_type -> meowhomo.engine.Empty
	0, // 7: meowhomo.engine.MihomoEngine.StreamLogs:input_type -> meowhomo.engine.Empty
	3, // 8: meowhomo.engine.MihomoEngine.Start:output_type -> meowhomo.engine.StatusResponse
	3, // 9: meowhomo.engine.MihomoEngine.Stop:output_type -> meowhomo.engine.StatusResponse
	3, // 10: meowhomo.engine.MihomoEngine.Reload:output_type -> meowhomo.engine.StatusResponse
	3, // 11: meowhomo.engine.MihomoEngine.GetStatus:output_type -> meowhomo.engine.StatusResponse
	4, // 12: meowhomo.engine.MihomoEngine.GetConnections:output_type -> meowhomo.engine.ConnectionsResponse
	6, // 13: meowhomo.engine.MihomoEngine.GetTraffic:output_type -> meowhomo.engine.TrafficResponse
	7, // 14: meowhomo.engine.MihomoEngine.StreamLogs:output_type -> meowhomo.engine.LogEntry
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
